name: Build Flet APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install flet
          pip install -r requirements.txt

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses

      - name: Build APK
        run: |
          yes | flet build apk --verbose

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-food-app-apk
          path: build/apk/*.apk
